### ISSUE TITLE
peer dependencies

### ISSUE THREAD

**Issue by maasencioh** [zakodium/eslint-config#18]
I think that is missing something on the dependencies of `@zakodium/eslint-config/typescript-react`, because on the latest install I have the following error for `eslint-plugin-react-hooks`, `eslint-plugin-react`, `eslint-plugin-jest` and `eslint-plugin-import`

```
ESLint: 8.1.0

ESLint couldn't find the plugin "eslint-plugin-import".

(The package "eslint-plugin-import" was not found when loaded as a Node module from the directory "C:\Users\maase\Documents\GitHub\zakodium\react-2dplot".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install eslint-plugin-import@latest --save-dev

The plugin "eslint-plugin-import" was referenced from the config file in ".eslintrc.yml » @zakodium/eslint-config/typescript-react » eslint-config-cheminfo-typescript#overrides[0]".
```

After installing them as dev-deps, I had the following error

```
Oops! Something went wrong! :(

ESLint: 8.1.0

Error: Failed to load parser '@typescript-eslint/parser' declared in '.eslintrc.yml » @zakodium/eslint-config/typescript-react » eslint-config-cheminfo-typescript#overrides[0]': Cannot find module '@typescript-eslint/parser'
Require stack:
- C:\Users\maase\Documents\GitHub\zakodium\react-2dplot\node_modules\eslint-config-cheminfo-typescript\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:15)
    at Function.resolve (node:internal/modules/cjs/helpers:99:19)
    at Object.resolve (C:\Users\maase\Documents\GitHub\zakodium\react-2dplot\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:1088:46)
    at ConfigArrayFactory._loadParser (C:\Users\maase\Documents\GitHub\zakodium\react-2dplot\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3235:39)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (C:\Users\maase\Documents\GitHub\zakodium\react-2dplot\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3030:43)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (C:\Users\maase\Documents\GitHub\zakodium\react-2dplot\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2971:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (C:\Users\maase\Documents\GitHub\zakodium\react-2dplot\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3064:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
```

**Comment by stropitek** [comment]
is @zakodium/eslint-config up to date and are you using a recent version of npm?

**Comment by maasencioh** [comment]
both yes, was using ncu to update all deps

**Comment by maasencioh** [comment]
It was because npm version, thank you, sorry for the late response
